name: release binary
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - name: build
      #   run: |
      #     env GOOS=darwin GOARCH=amd64 go build -o bin/main_darwin main.go
      #     env GOOS=linux GOARCH=amd64 go build -o bin/main_linux main.go
      #     env GOOS=windows GOARCH=amd64 go build -o bin/main_windows main.go
      
      - name: Get Tag name
        id: get_tag_name
        run: 
          TAG_NAME=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///g')
          echo ::set-output name=TAG_NAME::$TAG_NAME
      
      - name: debug
        run: echo ${{ steps.get_tag_name.outputs.TAG_NAME }}
    
      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       bin/main_darwin
      #       bin/main_linux
      #       bin/main_windows
      #     tag_name: ${TAG_NAME}
      #     body: |
      #       release body
      #     draft: false
      #     prerelease: false